# Generated by Django 4.2.13 on 2024-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='/public/static/myPassportSizePhoto.jpeg', upload_to='public/static/products/'),
        ),
    ]
