# Generated by Django 4.2.13 on 2024-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productmetainfoarmation',
            old_name='uid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='FoodOrderingSystem/public/static/myPassportSizePhoto.jpeg', upload_to='public/static/'),
        ),
    ]
